// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxV4kKnzSIom8654UkMFBMzKUqULK_4LQ',
    appId: '1:52470462324:web:ac3a7d2957c204f10c5e21',
    messagingSenderId: '52470462324',
    projectId: 'pomorodo-app',
    authDomain: 'pomorodo-app.firebaseapp.com',
    storageBucket: 'pomorodo-app.appspot.com',
    measurementId: 'G-1GHEY8173R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy0rWfKT8BVOdCaA3PmvqgQP83WhDCbTo',
    appId: '1:52470462324:android:c523fbf267cc96860c5e21',
    messagingSenderId: '52470462324',
    projectId: 'pomorodo-app',
    storageBucket: 'pomorodo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKO5JZI8MNdlCeH2j92cXVSrqR1VPIus0',
    appId: '1:52470462324:ios:2b223ce480286e610c5e21',
    messagingSenderId: '52470462324',
    projectId: 'pomorodo-app',
    storageBucket: 'pomorodo-app.appspot.com',
    androidClientId: '52470462324-nh6cfvg0dd9snpv8g2onsm168kus57la.apps.googleusercontent.com',
    iosClientId: '52470462324-1p17l9n0n2r7h64gtjskvmrrvo1b1bvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.pomodoro',
  );
}
